/**
 * Audit Action Types
 * Comprehensive list of all auditable actions in the system
 */
export enum AuditAction {
  // === Authentication ===
  OTP_REQUESTED = 'OTP_REQUESTED',
  OTP_VERIFIED = 'OTP_VERIFIED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  LOGOUT = 'LOGOUT',

  // === User Management ===
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_REACTIVATED = 'USER_REACTIVATED',

  // === KYC & Driver Verification ===
  KYC_UPLOAD_REQUESTED = 'KYC_UPLOAD_REQUESTED',
  KYC_UPLOAD_CONFIRMED = 'KYC_UPLOAD_CONFIRMED',
  BIOMETRIC_CHALLENGE_ISSUED = 'BIOMETRIC_CHALLENGE_ISSUED',
  BIOMETRIC_VERIFIED = 'BIOMETRIC_VERIFIED',
  BIOMETRIC_FAILED = 'BIOMETRIC_FAILED',
  DRIVER_APPROVED = 'DRIVER_APPROVED',
  DRIVER_REJECTED = 'DRIVER_REJECTED',
  DRIVER_SUSPENDED = 'DRIVER_SUSPENDED',
  DRIVER_REACTIVATED = 'DRIVER_REACTIVATED',

  // === Vehicle Management ===
  VEHICLE_REGISTERED = 'VEHICLE_REGISTERED',
  VEHICLE_UPDATED = 'VEHICLE_UPDATED',
  VEHICLE_DEACTIVATED = 'VEHICLE_DEACTIVATED',

  // === Ride Management ===
  RIDE_CREATED = 'RIDE_CREATED',
  RIDE_ACCEPTED = 'RIDE_ACCEPTED',
  RIDE_STARTED = 'RIDE_STARTED',
  RIDE_COMPLETED = 'RIDE_COMPLETED',
  RIDE_CANCELLED_BY_RIDER = 'RIDE_CANCELLED_BY_RIDER',
  RIDE_CANCELLED_BY_DRIVER = 'RIDE_CANCELLED_BY_DRIVER',
  RIDE_CANCELLED_BY_SYSTEM = 'RIDE_CANCELLED_BY_SYSTEM',

  // === Payment Processing ===
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',

  // === Driver Payouts ===
  PAYOUT_REQUESTED = 'PAYOUT_REQUESTED',
  PAYOUT_INITIATED = 'PAYOUT_INITIATED',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  PAYOUT_FAILED = 'PAYOUT_FAILED',

  // === Safety & Incidents ===
  SOS_TRIGGERED = 'SOS_TRIGGERED',
  SOS_ACKNOWLEDGED = 'SOS_ACKNOWLEDGED',
  SOS_RESOLVED = 'SOS_RESOLVED',
  SOS_ESCALATED = 'SOS_ESCALATED',
  SAFETY_CHECKLIST_COMPLETED = 'SAFETY_CHECKLIST_COMPLETED',
  FATIGUE_DETECTED = 'FATIGUE_DETECTED',

  // === Rating & Reviews ===
  RATING_SUBMITTED = 'RATING_SUBMITTED',

  // === Support & Tickets ===
  SUPPORT_TICKET_CREATED = 'SUPPORT_TICKET_CREATED',
  SUPPORT_TICKET_REPLIED = 'SUPPORT_TICKET_REPLIED',
  SUPPORT_TICKET_RESOLVED = 'SUPPORT_TICKET_RESOLVED',

  // === Data Privacy (GDPR Compliance) ===
  DATA_EXPORT_REQUESTED = 'DATA_EXPORT_REQUESTED',
  DATA_EXPORT_COMPLETED = 'DATA_EXPORT_COMPLETED',
  DATA_DELETION_REQUESTED = 'DATA_DELETION_REQUESTED',
  DATA_DELETION_COMPLETED = 'DATA_DELETION_COMPLETED',
  PII_ACCESS = 'PII_ACCESS',

  // === Promo & Marketing ===
  PROMO_CODE_APPLIED = 'PROMO_CODE_APPLIED',
  PROMO_CODE_CREATED = 'PROMO_CODE_CREATED',

  // === Admin Actions ===
  ADMIN_CONFIG_CHANGED = 'ADMIN_CONFIG_CHANGED',
  ADMIN_MANUAL_OVERRIDE = 'ADMIN_MANUAL_OVERRIDE',
}

/**
 * Audit Target Types
 * The type of entity being audited
 */
export enum AuditTargetType {
  USER = 'User',
  DRIVER = 'DriverProfile',
  RIDER = 'RiderProfile',
  RIDE = 'Ride',
  VEHICLE = 'Vehicle',
  PAYMENT = 'Payment',
  TRANSACTION = 'Transaction',
  PAYOUT = 'Payout',
  SOS = 'SosIncident',
  OTP = 'OtpCode',
  DOCUMENT = 'DriverDocument',
  SUPPORT_TICKET = 'SupportTicket',
  RATING = 'Rating',
  PROMO = 'PromoCode',
  CONFIG = 'SystemConfiguration',
}

/**
 * Critical actions that MUST be audited
 * Use this to ensure compliance with data protection requirements
 */
export const CRITICAL_AUDIT_ACTIONS: AuditAction[] = [
  // Payment & Financial
  AuditAction.PAYMENT_INITIATED,
  AuditAction.PAYMENT_PROCESSED,
  AuditAction.PAYMENT_FAILED,
  AuditAction.PAYMENT_REFUNDED,
  AuditAction.PAYOUT_REQUESTED,
  AuditAction.PAYOUT_COMPLETED,
  AuditAction.PAYOUT_FAILED,

  // Safety
  AuditAction.SOS_TRIGGERED,
  AuditAction.SOS_RESOLVED,

  // Suspensions
  AuditAction.DRIVER_SUSPENDED,
  AuditAction.DRIVER_REACTIVATED,
  AuditAction.USER_SUSPENDED,
  AuditAction.USER_REACTIVATED,

  // Data Privacy
  AuditAction.DATA_EXPORT_REQUESTED,
  AuditAction.DATA_EXPORT_COMPLETED,
  AuditAction.DATA_DELETION_REQUESTED,
  AuditAction.DATA_DELETION_COMPLETED,
  AuditAction.PII_ACCESS,

  // Cancellations
  AuditAction.RIDE_CANCELLED_BY_RIDER,
  AuditAction.RIDE_CANCELLED_BY_DRIVER,
  AuditAction.RIDE_CANCELLED_BY_SYSTEM,
];
